# Generated by Django 2.0.7 on 2022-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('my_field', models.CharField(choices=[('a', 'тренерки'), ('b', 'пижами'), ('c', 'блузи')], max_length=1)),
                ('kolicina', models.IntegerField()),
                ('velicina', models.CharField(choices=[('a', 'S'), ('b', 'M'), ('c', 'L'), ('d', 'XL')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
